accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(),name="login"),
    path("logout/", LogoutView.as_view(),name="logout"),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recordapp/", include("recordapp.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recordapp/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "recordapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/create", views.post_create, name="post"),
    path("post/<slug:slug>/", views.detail, name="detail"),
    path("post/<slug:slug>/update", views.detail_update, name="detail_update"),
    path("post/<slug:slug>/delete", views.detail_delete, name="detail_delete"),
    path("category/<int:category_id>/posts/", views.category_list, name="category_list"),
    path("gallery/", views.gallery, name="gallery"),
       
]

accounts/models.py
from django.db import models

# Create your models here.

recordapp/models.py
from django.db import models
from pathlib import Path

class Category(models.Model):
    name = models.CharField(verbose_name='カテゴリー', max_length=50)
    
    class Meta:
        verbose_name = 'カテゴリー'
        verbose_name_plural = 'カテゴリー一覧'
        
    def __str__(self):
        return self.name

class Post(models.Model):  
    slug = models.SlugField(blank=True, editable=True, unique=True)
    date = models.DateField(verbose_name='投稿日')
    what_done = models.TextField(verbose_name='本日の作業内容')
    what_not_done = models.TextField(verbose_name='本日の課題', blank=True)
    what_learned = models.TextField(verbose_name='本日の取得スキル', blank=True)
    summary_image = models.ImageField(upload_to='study_summaries/', verbose_name='まとめノート', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='カテゴリー', related_name='posts', null=True, blank=True)

    
    class Meta:
        verbose_name = '勉強記録'
        verbose_name_plural = '勉強記録一覧'

    def __str__(self):
        return f'{self.slug} - {self.date} - {self.what_done}'
    
    def save(self, *args, **kwargs):
        # slugが空の場合はIDを使ってslugを生成
        if not self.slug:
            # 一度保存してIDを取得し、そのIDをslugに設定
            super().save(*args, **kwargs)
            self.slug = str(self.id)  # IDをslugに設定
            super().save(*args, **kwargs)  # もう一度保存してslugを更新
        else:
            super().save(*args, **kwargs)
            
    # ファイルに保存された画像を削除する
    def delete(self, *args, **kwargs):
        summary_image =self.summary_image
        super().delete(*args, **kwargs)
        if summary_image:
            Path(summary_image.path).unlink(missing_ok=True)

recordapp/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["date", "what_done","what_not_done","what_learned","summary_image","category"]
        
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['what_done'].widget.attrs['class'] = 'what-done-field-class'

accounts/views.py
from django.shortcuts import render

# Create your views here.

recordapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .models import Post, Category
from .forms import PostForm 
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(View):
    def get(self, request):
        # posts = Post.objects.all()  # データベースから全てのPostを取得
        posts = Post.objects.order_by("-date")  # データベースから全てのPostを取得
        return render(request, "recordapp/index.html", {"posts": posts})

class PostCreateView(LoginRequiredMixin,View):
    def get(self, request):
        form = PostForm()
        return render(request, "recordapp/index_form.html", {"form":form})
    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("recordapp:index")
        return render(request, "recordapp/index_form.html", {"form":form})
        
class PostDetailView(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, "recordapp/detail.html", {"post": post})
    
class PostUpdateView(LoginRequiredMixin,View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        form = PostForm(instance=post)
        return render(request, "recordapp/detail_update.html", {"form": form})
    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("recordapp:detail", slug=slug)
        return render(request, "recordapp/index_form.html", {"form":form})

class PostDeleteView(LoginRequiredMixin,View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        return render(request, "recordapp/detail_delete.html", {"post": post})
    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        post.delete()
        return redirect("recordapp:index")

class CategoryListView(View):
    def get(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        posts = Post.objects.filter(category=category)
        context = {
            "category": category,
            "posts": posts  
        }
        return render(request, "recordapp/category_list.html", context)
    
class GalleryView(View):
    def get(self, request):
        posts = Post.objects.order_by('-date')[:6]   
        return render(request, "recordapp/gallery.html", {"posts": posts})

index = IndexView.as_view()
post_create =  PostCreateView.as_view()
detail = PostDetailView.as_view()
detail_update = PostUpdateView.as_view()
detail_delete = PostDeleteView.as_view()
category_list = CategoryListView.as_view()
gallery = GalleryView.as_view()

templates/recordapp/base.html
<!DOCTYPE html>
<html lang="jp">
<head>
    {% load static %}  <!-- staticタグを読み込む -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>study_record</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/recordapp/category_list.html
{% extends "recordapp/base.html" %}
{% block content %}
<h2>{{ category.name }}</h2>
<ul>
    {% for post in posts %}
    <li>{{ post.date }}:{{ post.what_done }} <a href="{% url 'recordapp:detail' post.slug %}">詳細</a></li>
    
    {% endfor %}
</ul>
<a href="{% url 'recordapp:index' %}">一覧に戻る</a>
{% endblock %}

templates/recordapp/detail.html
{% extends "recordapp/base.html" %}
{% block content %}
<h2>学習記録</h2>
<div class="post">
    <p>本日の作業内容：{{ post.what_done }}</p>
    <p>日時：{{ post.date }}</p>
    <p>本日の課題：{{ post.what_not_done }}</p>
    <p>本日の取得スキル：{{ post.what_learned }}</p>
    <div>まとめノート
        {% if post.summary_image %}
        <img src="{{ post.summary_image.url }}" alt="まとめノート">
        {% else %}
            <p>画像はありません</p>
        {% endif %}
    </div>
</div>
    {% if post.category %}
        <a href="{% url 'recordapp:category_list' post.category.id %}">{{ post.category.name}}</a>
    {% else %}
        <p>この投稿にはカテゴリーがありません。</p>
    {% endif %}


{% if user.is_authenticated %}
<a href="{% url 'recordapp:detail_update' post.slug %}">編集</a><br>
<a href="{% url 'recordapp:detail_delete' post.slug %}">削除</a><br>
{% endif %}
<a href="{% url 'recordapp:index' %}">一覧に戻る</a>

{% endblock %}

templates/recordapp/detail_delete.html
{% extends "recordapp/base.html" %}
{% block content %}
<form method="POST">
    {% csrf_token%}
    <p>このページを削除してよろしいですか</p>
    {{form.as_p}}
    <button type="submit">削除</button>
</form>
<h2>学習記録</h2>
<div class="post">
    <p>本日の作業内容：{{ post.what_done }}</p>
    <p>日時：{{ post.date }}</p>
    <p>本日の課題：{{ post.what_not_done }}</p>
    <p>本日の取得スキル：{{ post.what_learned }}</p>
    <div>まとめノート
        {% if post.summary_image %}
        <img src="{{ post.summary_image.url }}" alt="まとめノート">
        {% else %}
            <p>画像はありません</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/recordapp/detail_update.html
{% extends "recordapp/base.html" %}
{% block content %}
<h2>記録を編集する</h2>
<form method="POST" enctype="multipart/form-data" class="custom-form">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">更新</button>
</form>
{% endblock %}

templates/recordapp/gallery.html
{% extends "recordapp/base.html" %}
{% block content %}
<h2>記録ギャラリー一覧</h2>
<ul class="flex">
    {% for post in posts %}
    <li>
        <a href="{% url 'recordapp:detail' post.slug %}">
            <img src="{{ post.summary_image.url }}" alt="{{ post.what_done }}">
        </a>
        <div class="post-info">
            <p>{{ post.date }}<br> {{ post.what_done }}</p>
        </div>
        <a class="gallery_detail"href="{% url 'recordapp:detail' post.slug %}">詳細</a>
    </li>
    {% endfor %}
</ul>
<div style="text-align: center;"> 
    <a  href="{% url 'recordapp:index' %}">一覧表示</a>
</div>
{% endblock %}

templates/recordapp/index.html
    {% extends "recordapp/base.html" %}
    {% block content %}
    <h2>プログラミング学習記録</h2>

    {% if user.is_authenticated %}
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token%}
        <button type="submit">ログアウト</button>
    </form>
    <div class="record"><a  href="{% url 'recordapp:post'%}"><i class="fas fa-pencil-alt"></i>記録を書く</a></div>

    {% else %}
    <a  href="{% url 'accounts:login' %}">ログイン</a>
    {% endif %}

    <ul>
        {% for post in posts %}
            <li>{{ post.date }}<br>{{ post.what_done }}  
                <a class="detail" href="{% url 'recordapp:detail' post.slug%}">詳細</a>
                {% if post.category%}
                <a href="{% url 'recordapp:category_list' post.category.id%}">{{ post.category }}</a>
                {% else %}
                <p>カテゴリなし</p>
                {% endif %}
            </li>

        {% empty %}
            <li>勉強記録がありません。</li>
        {% endfor %}
    </ul>

    {% endblock %}

templates/recordapp/index_form.html
{% extends "recordapp/base.html" %}
{% block content %}
<h2>記録を書く</h2>
<form method="POST" enctype="multipart/form-data" class="custom-form">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">保存</button>
</form>
{% endblock %}